[versions]
# The latest versions are available at https://lambdaurora.dev/tools/import_quilt.html
kotlin_jvm = "1.7.10"

minecraft = "1.19.2"
quilt_mappings = "1.19.2+build.3"
quilt_loader = "0.17.1"

mod_menu = "4.0.6"

quilted_fabric_api = "4.0.0-beta.7+0.59.0-1.19.2"
quilt_kotlin = "0.1.3+kt.1.7.10+flk.1.8.2-SNAPSHOT"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

mod_menu = { module = "com.terraformersmc:modmenu", version.ref = "mod_menu" }

quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }
quilted_fabric_api_deprecated = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api-deprecated", version.ref = "quilted_fabric_api" }
quilt_kotlin = { module = "org.quiltmc.quilt-kotlin-libraries:quilt-kotlin-libraries", version.ref = "quilt_kotlin" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]
quilted_fabric_api = ["quilted_fabric_api", "quilted_fabric_api_deprecated"]

qol_mods = ["mod_menu"]

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version = "0.12.+" }
kotlin_jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin_jvm" }
